openapi: 3.0.3
info:
  contact:
    email: engineering@femsa.com
    name: Engineering Femsa
    url: https://github.com/digitalfemsa/openapi/issues
  description: Femsa sdk
  license:
    name: MIT-LICENSE
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Femsa API
  version: 2.1.0
servers:
- description: Femsa main server
  url: https://api.digitalfemsa.io
security:
- bearerAuth: []
paths:
  /api_keys:
    get:
      description: Consume the list of API keys you have.
      operationId: getApiKeys
      parameters:
      - description: Use for knowing which language to use
        examples:
          es:
            summary: for spanish request/response
            value: es
          en:
            summary: for english request/response
            value: en
        in: header
        name: Accept-Language
        required: false
        schema:
          default: es
          enum:
          - es
          - en
          type: string
      - description: "In the case of a holding company, the company id of the child\
          \ company to which will process the request."
        example: 6441b6376b60c3a638da80af
        in: header
        name: X-Child-Company-Id
        required: false
        schema:
          type: string
      - description: "The numbers of items to return, the maximum value is 250"
        in: query
        name: limit
        required: false
        schema:
          default: 20
          format: int32
          maximum: 250
          minimum: 1
          type: integer
      - description: next page
        in: query
        name: next
        required: false
        schema:
          type: string
      - description: previous page
        in: query
        name: previous
        required: false
        schema:
          type: string
      - description: "General search, e.g. by id, description, prefix"
        in: query
        name: search
        required: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/vnd.app-v2.2.0+json:
              schema:
                $ref: '#/components/schemas/get_api_keys_response'
          description: successful
        "401":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: Please include your access key in your request.
                  param: null
                  code: femsa.errors.authentication.missing_key
                log_id: 507f1f77bcf86cd799439011
                object: error
                type: authentication_error
              schema:
                $ref: '#/components/schemas/error'
          description: authentication error
        "500":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - debug_message: There was a runtime error and Femsa engineers have
                    been notified.
                  message: There was a runtime error and Femsa engineers have been
                    notified.
                  param: null
                  code: femsa.errors.api.system.general_failure
                object: error
                type: api_error
                log_id: 641b6f2b3cd9a50001515098
              schema:
                $ref: '#/components/schemas/error'
          description: internal server error
      security:
      - bearerAuth: []
      summary: Get list of Api Keys
      tags:
      - Api Keys
    post:
      description: Create an API key.
      operationId: createApiKey
      parameters:
      - description: Use for knowing which language to use
        examples:
          es:
            summary: for spanish request/response
            value: es
          en:
            summary: for english request/response
            value: en
        in: header
        name: Accept-Language
        required: false
        schema:
          default: es
          enum:
          - es
          - en
          type: string
      - description: "In the case of a holding company, the company id of the child\
          \ company to which will process the request."
        example: 6441b6376b60c3a638da80af
        in: header
        name: X-Child-Company-Id
        required: false
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/api_keys_create'
      responses:
        "200":
          content:
            application/vnd.app-v2.2.0+json:
              schema:
                $ref: '#/components/schemas/api_key_create_response'
          description: successful operation
        "401":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: Please include your access key in your request.
                  param: null
                  code: femsa.errors.authentication.missing_key
                log_id: 507f1f77bcf86cd799439011
                object: error
                type: authentication_error
              schema:
                $ref: '#/components/schemas/error'
          description: authentication error
        "422":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: The name does not exist.
                  param: payment_method.name
                  code: femsa.errors.parameter_validation.payment_method.name.nonexistent_token
                  debug_message: The name does not exist.
                log_id: 641b6d813cd9a50001515017
                object: error
                type: parameter_validation_error
              schema:
                $ref: '#/components/schemas/error'
          description: parameter validation error
        "500":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - debug_message: There was a runtime error and Femsa engineers have
                    been notified.
                  message: There was a runtime error and Femsa engineers have been
                    notified.
                  param: null
                  code: femsa.errors.api.system.general_failure
                object: error
                type: api_error
                log_id: 641b6f2b3cd9a50001515098
              schema:
                $ref: '#/components/schemas/error'
          description: internal server error
      security:
      - bearerAuth: []
      summary: Create Api Key
      tags:
      - Api Keys
  /api_keys/{id}:
    delete:
      description: Deletes an API key by its ID.
      operationId: deleteApiKey
      parameters:
      - description: Identifier of the resource
        example: 6307a60c41de27127515a575
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Use for knowing which language to use
        examples:
          es:
            summary: for spanish request/response
            value: es
          en:
            summary: for english request/response
            value: en
        in: header
        name: Accept-Language
        required: false
        schema:
          default: es
          enum:
          - es
          - en
          type: string
      responses:
        "200":
          content:
            application/vnd.app-v2.2.0+json:
              schema:
                $ref: '#/components/schemas/delete_api_keys_response'
          description: successful
        "401":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: Please include your access key in your request.
                  param: null
                  code: femsa.errors.authentication.missing_key
                log_id: 507f1f77bcf86cd799439011
                object: error
                type: authentication_error
              schema:
                $ref: '#/components/schemas/error'
          description: authentication error
        "404":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: The resource was not found.
                  param: null
                  code: femsa.errors.resource_not_found.entity
                  debug_message: The object Webhook "641b1d5662d7e00001eaa46b" could
                    not be found.
                log_id: 641b6c253cd9a50001514fae
                object: error
                type: resource_not_found_error
              schema:
                $ref: '#/components/schemas/error'
          description: not found entity
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
          description: parameter validation error
        "500":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - debug_message: There was a runtime error and Femsa engineers have
                    been notified.
                  message: There was a runtime error and Femsa engineers have been
                    notified.
                  param: null
                  code: femsa.errors.api.system.general_failure
                object: error
                type: api_error
                log_id: 641b6f2b3cd9a50001515098
              schema:
                $ref: '#/components/schemas/error'
          description: internal server error
      security:
      - bearerAuth: []
      summary: Delete Api Key
      tags:
      - Api Keys
    get:
      description: Gets an API key by its ID.
      operationId: getApiKey
      parameters:
      - description: Identifier of the resource
        example: 6307a60c41de27127515a575
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Use for knowing which language to use
        examples:
          es:
            summary: for spanish request/response
            value: es
          en:
            summary: for english request/response
            value: en
        in: header
        name: Accept-Language
        required: false
        schema:
          default: es
          enum:
          - es
          - en
          type: string
      - description: "In the case of a holding company, the company id of the child\
          \ company to which will process the request."
        example: 6441b6376b60c3a638da80af
        in: header
        name: X-Child-Company-Id
        required: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/vnd.app-v2.2.0+json:
              schema:
                $ref: '#/components/schemas/api_key_response'
          description: successful
        "401":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: Please include your access key in your request.
                  param: null
                  code: femsa.errors.authentication.missing_key
                log_id: 507f1f77bcf86cd799439011
                object: error
                type: authentication_error
              schema:
                $ref: '#/components/schemas/error'
          description: authentication error
        "404":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: The resource was not found.
                  param: null
                  code: femsa.errors.resource_not_found.entity
                  debug_message: The object Webhook "641b1d5662d7e00001eaa46b" could
                    not be found.
                log_id: 641b6c253cd9a50001514fae
                object: error
                type: resource_not_found_error
              schema:
                $ref: '#/components/schemas/error'
          description: not found entity
        "500":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - debug_message: There was a runtime error and Femsa engineers have
                    been notified.
                  message: There was a runtime error and Femsa engineers have been
                    notified.
                  param: null
                  code: femsa.errors.api.system.general_failure
                object: error
                type: api_error
                log_id: 641b6f2b3cd9a50001515098
              schema:
                $ref: '#/components/schemas/error'
          description: internal server error
      security:
      - bearerAuth: []
      summary: Get Api Key
      tags:
      - Api Keys
    put:
      description: Update an existing API key.
      operationId: updateApiKey
      parameters:
      - description: Identifier of the resource
        example: 6307a60c41de27127515a575
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Use for knowing which language to use
        examples:
          es:
            summary: for spanish request/response
            value: es
          en:
            summary: for english request/response
            value: en
        in: header
        name: Accept-Language
        required: false
        schema:
          default: es
          enum:
          - es
          - en
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api_key_update_request'
        required: true
      responses:
        "200":
          content:
            application/vnd.app-v2.2.0+json:
              schema:
                $ref: '#/components/schemas/api_key_response'
          description: successful operation
        "401":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: Please include your access key in your request.
                  param: null
                  code: femsa.errors.authentication.missing_key
                log_id: 507f1f77bcf86cd799439011
                object: error
                type: authentication_error
              schema:
                $ref: '#/components/schemas/error'
          description: authentication error
        "404":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: The resource was not found.
                  param: null
                  code: femsa.errors.resource_not_found.entity
                  debug_message: The object Webhook "641b1d5662d7e00001eaa46b" could
                    not be found.
                log_id: 641b6c253cd9a50001514fae
                object: error
                type: resource_not_found_error
              schema:
                $ref: '#/components/schemas/error'
          description: not found entity
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
          description: parameter validation error
        "500":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - debug_message: There was a runtime error and Femsa engineers have
                    been notified.
                  message: There was a runtime error and Femsa engineers have been
                    notified.
                  param: null
                  code: femsa.errors.api.system.general_failure
                object: error
                type: api_error
                log_id: 641b6f2b3cd9a50001515098
              schema:
                $ref: '#/components/schemas/error'
          description: internal server error
      security:
      - bearerAuth: []
      summary: Update Api Key
      tags:
      - Api Keys
  /balance:
    get:
      description: Get a company's balance
      operationId: getBalance
      parameters:
      - description: Use for knowing which language to use
        examples:
          es:
            summary: for spanish request/response
            value: es
          en:
            summary: for english request/response
            value: en
        in: header
        name: Accept-Language
        required: false
        schema:
          default: es
          enum:
          - es
          - en
          type: string
      responses:
        "200":
          content:
            application/vnd.app-v2.2.0+json:
              schema:
                $ref: '#/components/schemas/balance_response'
          description: successful
        "401":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: Please include your access key in your request.
                  param: null
                  code: femsa.errors.authentication.missing_key
                log_id: 507f1f77bcf86cd799439011
                object: error
                type: authentication_error
              schema:
                $ref: '#/components/schemas/error'
          description: authentication error
        "500":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - debug_message: There was a runtime error and Femsa engineers have
                    been notified.
                  message: There was a runtime error and Femsa engineers have been
                    notified.
                  param: null
                  code: femsa.errors.api.system.general_failure
                object: error
                type: api_error
                log_id: 641b6f2b3cd9a50001515098
              schema:
                $ref: '#/components/schemas/error'
          description: internal server error
      security:
      - bearerAuth: []
      summary: Get a company's balance
      tags:
      - Balances
  /charges:
    get:
      operationId: getCharges
      parameters:
      - description: Use for knowing which language to use
        examples:
          es:
            summary: for spanish request/response
            value: es
          en:
            summary: for english request/response
            value: en
        in: header
        name: Accept-Language
        required: false
        schema:
          default: es
          enum:
          - es
          - en
          type: string
      - description: "In the case of a holding company, the company id of the child\
          \ company to which will process the request."
        example: 6441b6376b60c3a638da80af
        in: header
        name: X-Child-Company-Id
        required: false
        schema:
          type: string
      - description: "The numbers of items to return, the maximum value is 250"
        in: query
        name: limit
        required: false
        schema:
          default: 20
          format: int32
          maximum: 250
          minimum: 1
          type: integer
      - description: "General order search, e.g. by mail, reference etc."
        in: query
        name: search
        required: false
        schema:
          type: string
      - description: next page
        in: query
        name: next
        required: false
        schema:
          type: string
      - description: previous page
        in: query
        name: previous
        required: false
        schema:
          type: string
      responses:
        "200":
          content:
            application/vnd.app-v2.2.0+json:
              schema:
                $ref: '#/components/schemas/get_charges_response'
          description: successful
        "401":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - message: Please include your access key in your request.
                  param: null
                  code: femsa.errors.authentication.missing_key
                log_id: 507f1f77bcf86cd799439011
                object: error
                type: authentication_error
              schema:
                $ref: '#/components/schemas/error'
          description: authentication error
        "422":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - debug_message: The "custom_field" parameter is not allowed
                  message: El parametro "custom_field" no está permitido
                  code: femsa.errors.parameter_validation.whitelist
                object: error
                type: parameter_validation_error
                log_id: 6462aa7c90fef20001633546
              schema:
                $ref: '#/components/schemas/error'
          description: whitelist validation error
        "500":
          content:
            application/vnd.app-v2.2.0+json:
              example:
                details:
                - debug_message: There was a runtime error and Femsa engineers have
                    been notified.
                  message: There was a runtime error and Femsa engineers have been
                    notified.
                  param: null
                  code: femsa.errors.api.system.general_failure
                object: error
                type: api_error
                log_id: 641b6f2b3cd9a50001515098
              schema:
                $ref: '#/components/schemas/error'
          description: internal server error
      security:
      - bearerAuth: []
      summary: Get A List of Charges
      tags:
      - Charges
  /charges/{id}:
    put:
      description: Updates an existing charge. Only `reference_id` can be updated.
      operationId: updateCharge
      parameters:
      - description: Identifier of the resource
        example: 6307a60c41de27127515a575
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Use for knowing which language to use
        examples:
          es:
            summary: for spanish request/response
            value: es
          en:
            summary: for english request/response
            value: en
        in: header
        name: Accept-Language
        required: false
        schema:
          default: es
          enum:
          - es
          - en
          type: string
      - description: "In the case of a holding company, the company id of the child\
          \ company to which will process the request."
        example: 6441b6376b60c3a638da80af
        in: header
        name: X-Child-Company-Id
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./requestBodies/charges/charge_update.yml
        required: true
      responses:
        "200":
          content:
            application/vnd.app-v2.2.0+json:
              schema:
                $ref: ./schemas/charges/charge_response.yml
          description: successful
        "401":
          $ref: ./resources/charges/../errors/401.yml
        "404":
          $ref: ./resources/charges/../errors/404.yml
        "422":
          $ref: ./resources/charges/../errors/422.yml
        "500":
          $ref: ./resources/charges/../errors/500.yml
      security:
      - bearerAuth: []
      summary: Update a charge
      tags:
      - Charges
  /orders/{id}/charges:
    $ref: ./resources/orders/order_charge_param.yml
  /companies:
    $ref: ./resources/companies/companies.yml
  /companies/{id}:
    $ref: ./resources/companies/company.yml
  /customers:
    $ref: ./resources/customers/create_customer.yml
  /customers/{id}:
    $ref: ./resources/customers/get_customer.yml
  /customers/{id}/fiscal_entities:
    $ref: ./resources/customers/create_customer_fiscal_entities.yml
  /customers/{id}/fiscal_entities/{fiscal_entities_id}:
    $ref: ./resources/customers/update_customer_fiscal_entities.yml
  /orders/{id}/discount_lines:
    $ref: ./resources/orders/discount_lines_param.yml
  /orders/{id}/discount_lines/{discount_lines_id}:
    $ref: ./resources/orders/update_order_discount_lines_param.yml
  /events:
    $ref: ./resources/events/events.yml
  /events/{id}:
    $ref: ./resources/events/event.yml
  /events/{event_id}/webhook_logs/{webhook_log_id}/resend:
    $ref: ./resources/events/events_resend.yml
  /logs:
    $ref: ./resources/logs/log.yml
  /logs/{id}:
    $ref: ./resources/logs/log_by_id.yml
  /orders:
    $ref: ./resources/orders/order.yml
  /orders/{id}:
    $ref: ./resources/orders/order_param.yml
  /orders/{id}/cancel:
    $ref: ./resources/orders/order_cancel_param.yml
  /orders/{id}/capture:
    $ref: ./resources/orders/order_capture_param.yml
  /orders/{id}/line_items:
    $ref: ./resources/orders/order_product_param.yml
  /orders/{id}/line_items/{line_item_id}:
    $ref: ./resources/orders/update_order_product_param.yml
  /orders/{id}/refunds:
    $ref: ./resources/orders/order_refunds_param.yml
  /orders/{id}/refunds/{refund_id}:
    $ref: ./resources/orders/order_cancel_refunds_param.yml
  /checkouts:
    $ref: ./resources/checkouts/checkouts.yml
  /checkouts/{id}:
    $ref: ./resources/checkouts/checkout.yml
  /checkouts/{id}/cancel:
    $ref: ./resources/checkouts/checkout_cancel.yml
  /checkouts/{id}/email:
    $ref: ./resources/checkouts/checkout_email.yml
  /checkouts/{id}/sms:
    $ref: ./resources/checkouts/checkout_sms.yml
  /customers/{id}/payment_sources:
    $ref: ./resources/customers/create_customer_payment_methods.yml
  /customers/{id}/payment_sources/{payment_method_id}:
    $ref: ./resources/customers/update_customer_payment_methods.yml
  /orders/{id}/shipping_lines:
    $ref: ./resources/orders/order_shipping_param.yml
  /orders/{id}/shipping_lines/{shipping_id}:
    $ref: ./resources/orders/update_order_shipping_param.yml
  /customers/{id}/shipping_contacts:
    $ref: ./resources/customers/create_customer_shipping_contacts.yml
  /customers/{id}/shipping_contacts/{shipping_contacts_id}:
    $ref: ./resources/customers/update_customer_shipping_contacts.yml
  /orders/{id}/tax_lines:
    $ref: ./resources/orders/order_tax_param.yml
  /orders/{id}/tax_lines/{tax_id}:
    $ref: ./resources/orders/update_order_tax_param.yml
  /transactions:
    $ref: ./resources/transactions/transactions.yml
  /transactions/{id}:
    $ref: ./resources/transactions/transaction.yml
  /transfers:
    $ref: ./resources/transfers/transfers.yml
  /transfers/{id}:
    $ref: ./resources/transfers/transfer.yml
  /webhook_keys:
    $ref: ./resources/webhook_keys/webhook_keys.yml
  /webhook_keys/{id}:
    $ref: ./resources/webhook_keys/webhook_key.yml
  /webhooks:
    $ref: ./resources/webhooks/webhooks.yml
  /webhooks/{id}:
    $ref: ./resources/webhooks/webhook.yml
  /webhooks/{id}/test:
    $ref: ./resources/webhooks/webhook_test.yml
components:
  parameters:
    accept_language:
      description: Use for knowing which language to use
      examples:
        es:
          summary: for spanish request/response
          value: es
        en:
          summary: for english request/response
          value: en
      in: header
      name: Accept-Language
      required: false
      schema:
        default: es
        enum:
        - es
        - en
        type: string
    x_child_company_id:
      description: "In the case of a holding company, the company id of the child\
        \ company to which will process the request."
      example: 6441b6376b60c3a638da80af
      in: header
      name: X-Child-Company-Id
      required: false
      schema:
        type: string
    limit:
      description: "The numbers of items to return, the maximum value is 250"
      in: query
      name: limit
      required: false
      schema:
        default: 20
        format: int32
        maximum: 250
        minimum: 1
        type: integer
    next_page:
      description: next page
      in: query
      name: next
      required: false
      schema:
        type: string
    previous_page:
      description: previous page
      in: query
      name: previous
      required: false
      schema:
        type: string
    id:
      description: Identifier of the resource
      example: 6307a60c41de27127515a575
      in: path
      name: id
      required: true
      schema:
        type: string
    search:
      description: "General order search, e.g. by mail, reference etc."
      in: query
      name: search
      required: false
      schema:
        type: string
  requestBodies:
    api_keys_create:
      content:
        application/json:
          schema:
            $ref: ./schemas/api_keys/api_key_request.yml
      description: requested field for a api keys
      required: true
  responses:
    "401":
      content:
        application/vnd.app-v2.2.0+json:
          example:
            details:
            - message: Please include your access key in your request.
              param: null
              code: femsa.errors.authentication.missing_key
            log_id: 507f1f77bcf86cd799439011
            object: error
            type: authentication_error
          schema:
            $ref: '#/components/schemas/error'
      description: authentication error
    "500":
      content:
        application/vnd.app-v2.2.0+json:
          example:
            details:
            - debug_message: There was a runtime error and Femsa engineers have been
                notified.
              message: There was a runtime error and Femsa engineers have been notified.
              param: null
              code: femsa.errors.api.system.general_failure
            object: error
            type: api_error
            log_id: 641b6f2b3cd9a50001515098
          schema:
            $ref: '#/components/schemas/error'
      description: internal server error
    "422":
      content:
        application/vnd.app-v2.2.0+json:
          example:
            details:
            - message: The name does not exist.
              param: payment_method.name
              code: femsa.errors.parameter_validation.payment_method.name.nonexistent_token
              debug_message: The name does not exist.
            log_id: 641b6d813cd9a50001515017
            object: error
            type: parameter_validation_error
          schema:
            $ref: '#/components/schemas/error'
      description: parameter validation error
    "404":
      content:
        application/vnd.app-v2.2.0+json:
          example:
            details:
            - message: The resource was not found.
              param: null
              code: femsa.errors.resource_not_found.entity
              debug_message: The object Webhook "641b1d5662d7e00001eaa46b" could not
                be found.
            log_id: 641b6c253cd9a50001514fae
            object: error
            type: resource_not_found_error
          schema:
            $ref: '#/components/schemas/error'
      description: not found entity
    "422_whitelist":
      content:
        application/vnd.app-v2.2.0+json:
          example:
            details:
            - debug_message: The "custom_field" parameter is not allowed
              message: El parametro "custom_field" no está permitido
              code: femsa.errors.parameter_validation.whitelist
            object: error
            type: parameter_validation_error
            log_id: 6462aa7c90fef20001633546
          schema:
            $ref: '#/components/schemas/error'
      description: whitelist validation error
  schemas:
    page:
      description: page metadata
      properties:
        next_page_url:
          description: URL of the next page.
          example: https://api.femsa.io/resources?limit=10&next=chrg_1
          nullable: true
          type: string
        previous_page_url:
          description: Url of the previous page.
          example: https://api.femsa.io/resources?limit=10&previous=chrg_1
          nullable: true
          type: string
      title: page metadata
      type: object
    pagination:
      description: pagination metadata
      properties:
        has_more:
          description: Indicates if there are more pages to be requested
          example: false
          type: boolean
        object:
          description: "Object type, in this case is list"
          example: list
          type: string
      required:
      - has_more
      - object
      title: pagination metadata
      type: object
    api_key_response:
      description: API keys model
      properties:
        id:
          description: Unique identifier of the API key
          example: 64625cc9f3e02c00163f5e4d
          type: string
        object:
          description: "Object name, value is 'api_key'"
          enum:
          - api_key
          example: api_key
          type: string
        active:
          description: Indicates if the API key is active
          example: true
          type: boolean
        livemode:
          description: Indicates if the API key is in production
          example: false
          type: boolean
        role:
          description: Indicates if the API key is private or public
          enum:
          - private
          - public
          example: private
          type: string
        description:
          description: A name or brief explanation of what this API key is used for
          example: online store
          nullable: true
          type: string
        prefix:
          description: The first few characters of the authentication_token
          example: key_rp
          type: string
        created_at:
          description: Unix timestamp in seconds of when the API key was created
          example: 1684167881
          format: int64
          type: integer
        updated_at:
          description: Unix timestamp in seconds of when the API key was last updated
          example: 1684167923
          format: int64
          type: integer
        deactivated_at:
          description: Unix timestamp in seconds of when the API key was deactivated
          format: int64
          nullable: true
          type: integer
          example: null
        deleted:
          description: Indicates if the API key was deleted
          example: false
          type: boolean
      required:
      - active
      - created_at
      - id
      - livemode
      - object
      - prefix
      - role
      - updated_at
      title: api_key_response
      type: object
    error:
      allOf:
      - $ref: ./schemas/errors/details.yml#/details
      - properties:
          log_id:
            description: log id
            example: 507f1f77bcf86cd799439011
            nullable: true
            type: string
          type:
            example: authentication_error
            type: string
          object:
            example: error
            type: string
        type: object
      description: err model
      title: error
    "422":
      description: parameter validation error
      type: object
    api_key_response_on_delete:
      description: api keys model
      properties:
        active:
          description: Indicates if the api key is active
          example: false
          type: boolean
        created_at:
          description: Unix timestamp in seconds of when the api key was created
          example: 1684167881
          format: int64
          type: integer
        description:
          description: A name or brief explanation of what this api key is used for
          example: online store
          type: string
        livemode:
          description: Indicates if the api key is in production
          example: false
          type: boolean
        prefix:
          description: The first few characters of the authentication_token
          example: key_rp
          type: string
        id:
          description: Unique identifier of the api key
          example: 64625cc9f3e02c00163f5e4d
          type: string
        object:
          description: "Object name, value is 'api_key'"
          enum:
          - api_key
          example: api_key
          type: string
        deleted:
          description: Indicates if the api key was deleted
          example: true
          type: boolean
        role:
          description: Indicates if the api key is private or public
          enum:
          - private
          - public
          example: private
          type: string
      required:
      - active
      - created_at
      - deleted
      - description
      - id
      - livemode
      - object
      - prefix
      - role
      title: api_key_response_delete
      type: object
    balance_response:
      description: balance model
      properties:
        available:
          description: The balance's available
          items:
            $ref: ./schemas/balances/balance_common_field.yml
          type: array
        pending:
          description: The balance's pending
          items:
            $ref: ./schemas/balances/balance_common_field.yml
          type: array
        retention_amount:
          description: The balance's retention amount
          items:
            $ref: ./schemas/balances/balance_common_field.yml
          type: array
        retained:
          description: The balance's retained
          items:
            $ref: ./schemas/balances/balance_common_field.yml
          type: array
        temporarily_retained:
          description: The balance's temporarily retained
          items:
            $ref: ./schemas/balances/balance_common_field.yml
          type: array
        target_retention_amount:
          description: The balance's target retention amount
          items:
            $ref: ./schemas/balances/balance_common_field.yml
          type: array
        conekta_retention:
          description: The balance's Femsa retention
          items:
            $ref: ./schemas/balances/balance_common_field.yml
          type: array
        cashout_retention_amount:
          description: The balance's cashout retention amount
          items:
            $ref: ./schemas/balances/balance_common_field.yml
          type: array
        target_collateral_amount:
          additionalProperties: true
          description: The balance's target collateral amount
          type: object
        gateway:
          additionalProperties: true
          description: The balance's gateway
          type: object
      required:
      - available
      - cashout_retention_amount
      - conekta_retention
      - gateway
      - pending
      - retained
      - retention_amount
      - target_collateral_amount
      - target_retention_amount
      - temporarily_retained
      title: balance_response
      type: object
    charge_response:
      properties:
        id:
          example: 696a682e1ef5ca00015698b7
          type: string
        livemode:
          example: true
          type: boolean
        created_at:
          example: 1768581166
          format: int64
          type: integer
        currency:
          example: MXN
          type: string
        failure_code:
          nullable: true
          type: string
          example: null
        failure_message:
          nullable: true
          type: string
          example: null
        channel:
          $ref: '#/components/schemas/charge_response_channel'
        payment_method:
          $ref: '#/components/schemas/charge_response_payment_method'
        object:
          enum:
          - charge
          example: charge
          type: string
        device_fingerprint:
          example: 6FR3chaU4Y1nGAW5NAGd1rcjAKa142Ba
          type: string
        description:
          example: Payment from order
          type: string
        is_refundable:
          example: false
          type: boolean
        reference_id:
          nullable: true
          type: string
          example: null
        status:
          example: expired
          type: string
        amount:
          example: 600000
          format: int64
          type: integer
        paid_at:
          format: int64
          nullable: true
          type: integer
          example: null
        customer_id:
          example: ""
          type: string
        order_id:
          example: ord_2zNwzJrfNC24uQUzq
          type: string
        refunds:
          $ref: '#/components/schemas/charge_response_refunds'
      required:
      - amount
      - created_at
      - currency
      - id
      - livemode
      - object
      - payment_method
      - status
      title: charge_response
      type: object
    get_api_keys_response:
      allOf:
      - $ref: '#/components/schemas/page'
      - $ref: '#/components/schemas/pagination'
      - properties:
          data:
            items:
              $ref: '#/components/schemas/api_key_response'
            type: array
        type: object
      title: get_api_keys_response
    api_key_create_response:
      allOf:
      - type: object
      - $ref: '#/components/schemas/api_key_response'
      title: api_key_create_response
    api_key_update_request:
      properties:
        active:
          description: Indicates whether the API key is active.
          example: true
          type: boolean
        description:
          description: A name or brief explanation of what this API key is used for.
          example: online store
          type: string
      title: api_key_update_request
      type: object
    delete_api_keys_response:
      allOf:
      - $ref: '#/components/schemas/api_key_response_on_delete'
      - properties:
          deleted:
            example: true
            type: boolean
        type: object
      title: delete_api_keys_response
    get_charges_response:
      allOf:
      - $ref: '#/components/schemas/pagination'
      - $ref: '#/components/schemas/page'
      - properties:
          data:
            items:
              $ref: '#/components/schemas/charge_response'
            type: array
        type: object
      title: get_charges_response
    charge_response_channel:
      properties:
        segment:
          example: Checkout
          type: string
        checkout_request_id:
          example: f3a5bfc1-ba1c-474f-9687-46d8b75ffc90
          type: string
        checkout_request_type:
          example: Integration
          type: string
        id:
          example: channel_2zNxD65G8MBNkYksy
          type: string
      type: object
    charge_response_payment_method:
      discriminator:
        mapping:
          cash_payment: charge_payment_method_cash_response.yml#/payment_method_cash
        propertyName: object
      oneOf:
      - $ref: ./schemas/charges/charge_payment_method_cash_response.yml#/payment_method_cash
      title: charge_response_payment_method
    charge_response_refunds_data:
      properties:
        amount:
          example: -15000
          format: int64
          type: integer
        auth_code:
          example: "867372"
          nullable: true
          type: string
        created_at:
          example: 1678226878
          format: int64
          type: integer
        expires_at:
          description: refund expiration date
          example: 1678226878
          format: int64
          nullable: true
          type: integer
        id:
          example: 6407b5bee1329a000175ba11
          type: string
        object:
          enum:
          - refund
          example: refund
          type: string
        status:
          description: refund status
          example: pending
          nullable: true
          type: string
        payout_id:
          example: 6fca054a-8519-4c43-971e-cea35cc519bb
          nullable: true
          type: string
        reference:
          description: payout reference for oxxo stores
          example: "12002000778626"
          nullable: true
          type: string
      required:
      - amount
      - created_at
      - id
      - object
      title: charge_response_refunds_data
      type: object
    charge_response_refunds:
      allOf:
      - $ref: ./schemas/pagination/pagination.yml
      - $ref: ./schemas/pagination/page.yml
      - properties:
          data:
            description: refunds
            items:
              $ref: '#/components/schemas/charge_response_refunds_data'
            type: array
        type: object
      nullable: true
      title: charge_response_refunds
      type: object
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
